/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * FuelPro Enterprise Reports Platform v2.0
 * Phase 1.3 — Enterprise Component Library Framework
 *
 * Enterprise Export Suite.
 * Real handlers for PDF (pdfGenerator), Excel (excelExporter), CSV,
 * WhatsApp (whatsappShare), and Print — all driven by the actual
 * verified register data (Rules #24/#25). No decorative dead buttons.
 */

import React, { useState } from 'react';
import { FileText, FileSpreadsheet, FileDown, Share2, Printer, Check } from 'lucide-react';
import { EnterpriseComponentRegistry } from '../EnterpriseComponentRegistry';
import { generatePdfBlob } from '../../../../../utils/pdfGenerator';
import { exportToExcel } from '../../../../../utils/excelExporter';
import { generateWhatsAppLink } from '../../../../../utils/whatsappShare';
import { logger } from '../../../../../lib/logger';

EnterpriseComponentRegistry.getInstance().register({
  id: 'ECL-EXPORT',
  version: '1.1.0',
  owner: 'ECL Core Team',
  category: 'EXPORT',
  status: 'PRODUCTION',
  accessibility: 'WCAG_AA',
  themeSupport: true
});

export interface EnterpriseExportProps {
  /** Report ID used in filenames (e.g. 'B-001') */
  reportId: string;
  title: string;
  titleUr?: string;
  /** Raw register rows keyed by column accessor */
  rows: Record<string, any>[];
  /** Column definitions (id/header/accessor/isNumeric/isCurrency) */
  columns: { id: string; header: string; accessor: string; isNumeric?: boolean }[];
  language?: 'en' | 'ur';
}

/**
 * Reusable export handlers — shared by the EnterpriseExport button suite and
 * the UniversalToolbar's global Export action (so a report can be exported
 * from either place with identical, verified register data).
 */
export const exportRegisterData = {
  baseName(reportId: string, stamp = new Date().toISOString().split('T')[0]): string {
    return `${reportId}-${stamp}`;
  },

  csv(reportId: string, rows: Record<string, any>[], columns: { header: string; accessor: string }[]): void {
    const escape = (v: unknown) => {
      const s = v === null || v === undefined ? '' : String(v);
      return /[,"\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
    };
    const header = columns.map(c => escape(c.header)).join(',');
    const lines = rows.map(r => columns.map(c => escape(r[c.accessor])).join(','));
    const csv = [header, ...lines].join('\n');
    const blob = new Blob(['\ufeff' + csv], { type: 'text/csv;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${exportRegisterData.baseName(reportId)}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  },

  async excel(reportId: string, headerLabel: string, rows: Record<string, any>[], columns: { header: string; accessor: string; isNumeric?: boolean }[]): Promise<void> {
    exportToExcel({
      fileName: exportRegisterData.baseName(reportId),
      sheetName: headerLabel.slice(0, 30),
      title: headerLabel,
      columns: columns.map(c => ({ header: c.header, key: c.accessor, width: c.isNumeric ? 16 : 22 })),
      data: rows
    });
  },

  async pdf(reportId: string, headerLabel: string, rows: Record<string, any>[], columns: { label: string; accessor: string }[]): Promise<void> {
    const blob = await generatePdfBlob({
      title: headerLabel,
      data: rows,
      columns: columns.map(c => ({ key: c.accessor, label: c.label }))
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${exportRegisterData.baseName(reportId)}.pdf`;
    a.click();
    URL.revokeObjectURL(url);
  },

  whatsapp(headerLabel: string, reportId: string, rows: Record<string, any>[], columns: { header: string; accessor: string }[]): void {
    const limit = Math.min(rows.length, 20);
    let text = `*${headerLabel} — FuelPro* (${reportId})\n`;
    text += `Date: ${new Date().toLocaleDateString()}\n\n`;
    for (let i = 0; i < limit; i++) {
      const parts = columns.slice(0, 3).map(c => `${c.header}: ${rows[i]?.[c.accessor] ?? '-'}`);
      text += `- ${parts.join(' | ')}\n`;
    }
    if (rows.length > limit) text += `\n...and ${rows.length - limit} more records.\n`;
    text += `\nGenerated by FuelPro Enterprise Reports — 100% live data.`;
    window.open(generateWhatsAppLink('', text), '_blank');
  },

  print(): void {
    window.print();
  }
};

export function EnterpriseExport({ reportId, title, titleUr, rows, columns, language = 'en' }: EnterpriseExportProps) {
  const [busy, setBusy] = useState<string | null>(null);
  const [done, setDone] = useState<string | null>(null);
  const isEn = language === 'en';

  const headerLabel = isEn ? title : (titleUr || title);

  const flashDone = (format: string) => {
    setDone(format);
    setTimeout(() => setDone(null), 2200);
  };

  const handleCSV = () => {
    exportRegisterData.csv(reportId, rows, columns);
    flashDone('CSV');
  };

  const handleExcel = async () => {
    setBusy('Excel');
    try {
      await exportRegisterData.excel(reportId, headerLabel, rows, columns);
      flashDone('Excel');
    } catch (e: any) {
      logger.error('[EnterpriseExport] Excel export failed:', e);
    } finally {
      setBusy(null);
    }
  };

  const handlePDF = async () => {
    setBusy('PDF');
    try {
      await exportRegisterData.pdf(reportId, headerLabel, rows, columns.map(c => ({ label: c.header, accessor: c.accessor })));
      flashDone('PDF');
    } catch (e: any) {
      logger.error('[EnterpriseExport] PDF export failed:', e);
    } finally {
      setBusy(null);
    }
  };

  const handleWhatsApp = () => {
    exportRegisterData.whatsapp(headerLabel, reportId, rows, columns);
    flashDone('WhatsApp');
  };

  const handlePrint = () => {
    exportRegisterData.print();
    flashDone('Print');
  };

  const buttonStyle: React.CSSProperties = {
    display: 'flex', alignItems: 'center', gap: 6,
    padding: '6px 12px', borderRadius: 6,
    border: '1px solid var(--border-main)',
    backgroundColor: 'var(--bg-app)', color: 'var(--text-main)',
    cursor: 'pointer', fontSize: 12, fontWeight: 600,
    transition: 'all 0.15s', minHeight: 32
  };

  const renderButton = (key: string, icon: React.ReactNode, label: string, onClick: () => void) => (
    <button
      key={key}
      onClick={onClick}
      disabled={busy !== null}
      style={{ ...buttonStyle, opacity: busy === key ? 0.55 : 1, cursor: busy === key ? 'wait' : 'pointer' }}
      title={isEn ? `Export as ${label}` : `${label} کے طور پر ایکسپورٹ کریں`}
    >
      {done === key ? <Check size={13} style={{ color: 'var(--color-success)' }} /> : icon}
      {label}
    </button>
  );

  return (
    <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', alignItems: 'center' }}>
      <span style={{ fontWeight: 600, color: 'var(--text-muted)', alignSelf: 'center', marginRight: 4, fontSize: 12 }}>
        {isEn ? 'Export:' : 'ایکسپورٹ:'}
      </span>
      <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
        {renderButton('PDF', <FileText size={13} style={{ color: 'var(--color-danger)' }} />, 'PDF', handlePDF)}
        {renderButton('Excel', <FileSpreadsheet size={13} style={{ color: 'var(--color-success)' }} />, 'Excel', handleExcel)}
        {renderButton('CSV', <FileDown size={13} />, 'CSV', handleCSV)}
        {renderButton('WhatsApp', <Share2 size={13} style={{ color: 'var(--color-accent)' }} />, 'WhatsApp', handleWhatsApp)}
        {renderButton('Print', <Printer size={13} />, 'Print', handlePrint)}
      </div>
    </div>
  );
}
