/**
 * @license SPDX-License-Identifier: Apache-2.0
 *
 * FuelPro Enterprise Reports Platform v3.0
 * All 54 Business Center Report Configurations
 *
 * ENTERPRISE RULE #130 — EVERY BUSINESS REPORT IS A COMPLETE WORKSPACE
 *
 * Provides ReportConfig specifications for all 54 report IDs across 10 domain groups:
 * Fuel Operations, Inventory, Purchases, Finance, Ledgers, Customers, Suppliers,
 * Staff, Pricing, and Analytics.
 *
 * Every report specifies:
 * - Title & TitleUr
 * - QueryPlan (base collection + optional joins)
 * - Context-aware KPIs
 * - Report-specific SearchConfig
 * - Dynamic FilterGroups (pills/presets)
 * - QuickActions & SavedViews
 * - Register columns with sorting, numeric/currency flags, and summary fields
 * - Exports array
 */

import { ReportConfig } from '../engines/types';
import { ReportConfigRegistry } from '../engines/ReportConfigLoader';

export const ALL_BUSINESS_REPORTS: ReportConfig[] = [
  // ──────────────────────────────────────────────
  // 🏢 DOMAIN WORKSPACE HOMES (ENTERPRISE RULE #132)
  // ──────────────────────────────────────────────
  {
    reportId: 'DOMAIN_FUEL_HOME',
    engineType: 'BusinessDashboard',
    rendererProfile: 'Executive',
    title: 'Fuel Operations Workspace',
    titleUr: 'فیول آپریشنز ورک اسپیس',
    queryPlan: { base: 'SALES' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager', 'Accountant', 'Supervisor', 'Cashier'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'todaySales', label: "Today's Fuel Sales", labelUr: 'آج کی سیلز', formulaId: 'FORMULA_GROSS_REVENUE', displayType: 'simple', unit: '₨' },
      { id: 'todayLiters', label: 'Liters Sold Today', labelUr: 'آج فروخت لیٹر', formulaId: 'FORMULA_TOTAL_LITERS_SOLD', displayType: 'simple', unit: 'L' },
      { id: 'activeNozzleCount', label: 'Active Nozzles', labelUr: 'فعال نوزلز', displayType: 'simple', unit: '' },
    ],
    register: {
      columns: [
        { id: 'date', header: 'Date', headerUr: 'تاریخ', accessor: 'date', isDate: true, sortable: true },
        { id: 'invoiceNo', header: 'Invoice #', headerUr: 'انوائس #', accessor: 'invoiceNo', sortable: true },
        { id: 'productName', header: 'Product', headerUr: 'پروڈکٹ', accessor: 'productName' },
        { id: 'quantity', header: 'Liters', headerUr: 'لیٹر', accessor: 'quantity', isNumeric: true },
        { id: 'totalAmount', header: 'Amount', headerUr: 'رقم', accessor: 'totalAmount', isCurrency: true },
      ],
      defaultSortColumn: 'date',
      defaultSortDirection: 'desc',
      summaryFields: ['quantity', 'totalAmount'],
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
    quickActions: [
      { id: 'newSale', label: '+ Fuel Sale', labelUr: '+ فیول سیل', icon: '⛽', targetReportId: 'FS_REGISTER', color: 'emerald' },
      { id: 'viewShifts', label: 'Shift Sales', labelUr: 'شفٹ سیلز', icon: '⏱️', targetReportId: 'C2', color: 'blue' },
      { id: 'viewNozzles', label: 'Nozzle Sales', labelUr: 'نوزل سیلز', icon: '📋', targetReportId: 'FS_NOZZLE', color: 'purple' },
    ],
  },
  {
    reportId: 'DOMAIN_INV_HOME',
    engineType: 'StockDashboard',
    rendererProfile: 'Inventory',
    title: 'Inventory & Tank Stock Workspace',
    titleUr: 'انوینٹری ورک اسپیس',
    queryPlan: { base: 'TANKS' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager', 'Supervisor'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'stockTotal', label: 'Total Stock on Hand', labelUr: 'موجودہ اسٹاک', formulaId: 'FORMULA_CURRENT_STOCK', displayType: 'simple', unit: 'L' },
      { id: 'tankFillAvg', label: 'Avg Tank Fill', labelUr: 'اوسط بھرائی', formulaId: 'FORMULA_TANK_FILL_PERCENT', displayType: 'gauge', unit: '%' },
    ],
    register: {
      columns: [
        { id: 'name', header: 'Tank Name', headerUr: 'ٹینک کا نام', accessor: 'name', sortable: true },
        { id: 'product', header: 'Product', headerUr: 'پروڈکٹ', accessor: 'product' },
        { id: 'capacity', header: 'Capacity', headerUr: 'گنجائش', accessor: 'capacity', isNumeric: true },
        { id: 'currentStock', header: 'Current Stock', headerUr: 'موجودہ اسٹاک', accessor: 'currentStock', isNumeric: true },
      ],
      defaultSortColumn: 'name',
      defaultSortDirection: 'asc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'DOMAIN_PUR_HOME',
    engineType: 'SalesRegister',
    rendererProfile: 'Operational',
    title: 'Purchases & Deliveries Workspace',
    titleUr: 'خریداری ورک اسپیس',
    queryPlan: { base: 'FUEL_PURCHASES' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager', 'Accountant'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'purchasesTotal', label: 'Total Fuel Purchases', labelUr: 'کل خریداری', displayType: 'simple', unit: '₨' },
    ],
    register: {
      columns: [
        { id: 'date', header: 'Date', headerUr: 'تاریخ', accessor: 'date', isDate: true, sortable: true },
        { id: 'supplierName', header: 'Supplier', headerUr: 'سپلائر', accessor: 'supplierName' },
        { id: 'product', header: 'Product', headerUr: 'پروڈکٹ', accessor: 'product' },
        { id: 'liters', header: 'Liters Delivered', headerUr: 'لیٹر ڈیلیوری', accessor: 'liters', isNumeric: true },
        { id: 'totalAmount', header: 'Amount', headerUr: 'رقم', accessor: 'totalAmount', isCurrency: true },
      ],
      defaultSortColumn: 'date',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'DOMAIN_FIN_HOME',
    engineType: 'CashSummary',
    rendererProfile: 'Financial',
    title: 'Finance & Banking Workspace',
    titleUr: 'مالیات ورک اسپیس',
    queryPlan: { base: 'CASH_LEDGER' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Accountant'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'cashPosition', label: 'Cash & Bank Liquidity', labelUr: 'نقد و بینک بیلنس', formulaId: 'FORMULA_CASH_BALANCE', displayType: 'simple', unit: '₨' },
    ],
    register: {
      columns: [
        { id: 'date', header: 'Date', headerUr: 'تاریخ', accessor: 'date', isDate: true, sortable: true },
        { id: 'voucherNo', header: 'Voucher #', headerUr: 'واؤچر #', accessor: 'voucherNo' },
        { id: 'description', header: 'Particulars', headerUr: 'تفصیل', accessor: 'description' },
        { id: 'amount', header: 'Amount', headerUr: 'رقم', accessor: 'amount', isCurrency: true },
      ],
      defaultSortColumn: 'date',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'DOMAIN_LEDGER_HOME',
    engineType: 'CustomerLedger',
    rendererProfile: 'Financial',
    title: 'General Ledgers Workspace',
    titleUr: 'لیجر ورک اسپیس',
    queryPlan: { base: 'CUSTOMERS' },
    cacheTier: 'cached',
    visibleTo: ['Owner', 'Manager', 'Accountant'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'totalReceivables', label: 'Total Customer Receivables', labelUr: 'کل کسٹمر بقایا جات', formulaId: 'FORMULA_CUSTOMER_RECEIVABLE', displayType: 'simple', unit: '₨' },
    ],
    register: {
      columns: [
        { id: 'name', header: 'Account Name', headerUr: 'عنوان', accessor: 'name', sortable: true },
        { id: 'balance', header: 'Outstanding Balance', headerUr: 'بقایا بیلنس', accessor: 'balance', isCurrency: true },
      ],
      defaultSortColumn: 'balance',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'DOMAIN_CUS_HOME',
    engineType: 'CustomerLedger',
    rendererProfile: 'Operational',
    title: 'Customer Directory & Credit Workspace',
    titleUr: 'گاہک ورک اسپیس',
    queryPlan: { base: 'CUSTOMERS' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager', 'Accountant'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'cusReceivable', label: 'Customer Outstanding', labelUr: 'گاہک بقایا', displayType: 'simple', unit: '₨' },
    ],
    register: {
      columns: [
        { id: 'name', header: 'Customer Name', headerUr: 'کسٹمر نام', accessor: 'name', sortable: true },
        { id: 'phone', header: 'Phone', headerUr: 'فون', accessor: 'phone' },
        { id: 'balance', header: 'Outstanding Due', headerUr: 'بقایا رقم', accessor: 'balance', isCurrency: true },
      ],
      defaultSortColumn: 'balance',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'DOMAIN_SUP_HOME',
    engineType: 'CustomerLedger',
    rendererProfile: 'Operational',
    title: 'Supplier & Payables Workspace',
    titleUr: 'سپلائر ورک اسپیس',
    queryPlan: { base: 'SUPPLIERS' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager', 'Accountant'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'supPayable', label: 'Supplier Total Payable', labelUr: 'سپلائرز واجب الادا', displayType: 'simple', unit: '₨' },
    ],
    register: {
      columns: [
        { id: 'name', header: 'Supplier Name', headerUr: 'سپلائر نام', accessor: 'name', sortable: true },
        { id: 'phone', header: 'Phone', headerUr: 'فون', accessor: 'phone' },
        { id: 'balance', header: 'Payable Balance', headerUr: 'بیلنس', accessor: 'balance', isCurrency: true },
      ],
      defaultSortColumn: 'balance',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'DOMAIN_STF_HOME',
    engineType: 'Variance',
    rendererProfile: 'Operational',
    title: 'Staff & Shift History Workspace',
    titleUr: 'اسٹاف ورک اسپیس',
    queryPlan: { base: 'EMPLOYEES' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'staffCount', label: 'Station Employees', labelUr: 'کل ملازمین', displayType: 'simple', unit: '' },
    ],
    register: {
      columns: [
        { id: 'name', header: 'Staff Name', headerUr: 'نام', accessor: 'name', sortable: true },
        { id: 'role', header: 'Role', headerUr: 'عہدہ', accessor: 'role' },
        { id: 'salary', header: 'Salary', headerUr: 'تنخواہ', accessor: 'salary', isCurrency: true },
      ],
      defaultSortColumn: 'name',
      defaultSortDirection: 'asc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'DOMAIN_PRC_HOME',
    engineType: 'ProfitReport',
    rendererProfile: 'Operational',
    title: 'Pricing & Fuel Rates Workspace',
    titleUr: 'قیمتیں ورک اسپیس',
    queryPlan: { base: 'PRODUCTS' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'petrolRate', label: 'Active Petrol Rate', labelUr: 'پٹرول ریٹ', displayType: 'simple', unit: '₨' },
    ],
    register: {
      columns: [
        { id: 'productName', header: 'Product Name', headerUr: 'پروڈکٹ نام', accessor: 'productName', sortable: true },
        { id: 'saleRate', header: 'Retail Rate', headerUr: 'فروخت ریٹ', accessor: 'saleRate', isCurrency: true },
        { id: 'purchaseRate', header: 'Purchase Cost', headerUr: 'خریداری لاگت', accessor: 'purchaseRate', isCurrency: true },
      ],
      defaultSortColumn: 'productName',
      defaultSortDirection: 'asc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'DOMAIN_ANL_HOME',
    engineType: 'BusinessDashboard',
    rendererProfile: 'Executive',
    title: 'Executive Analytics & Control Room',
    titleUr: 'ایگزیکٹو کنٹرول روم',
    queryPlan: { base: 'SALES' },
    cacheTier: 'realtime',
    visibleTo: ['Owner'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'execRevenue', label: 'Gross Revenue', labelUr: 'کل آمدن', formulaId: 'FORMULA_GROSS_REVENUE', displayType: 'simple', unit: '₨' },
      { id: 'execProfit', label: 'True Profit', labelUr: 'اصل منافع', formulaId: 'FORMULA_TRUE_PROFIT', displayType: 'simple', unit: '₨' },
    ],
    register: {
      columns: [
        { id: 'date', header: 'Date', headerUr: 'تاریخ', accessor: 'date', isDate: true },
        { id: 'invoiceNo', header: 'Invoice #', headerUr: 'انوائس #', accessor: 'invoiceNo' },
        { id: 'totalAmount', header: 'Amount', headerUr: 'رقم', accessor: 'totalAmount', isCurrency: true },
      ],
      defaultSortColumn: 'date',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },

  // ──────────────────────────────────────────────
  // ⛽ FUEL OPERATIONS
  // ──────────────────────────────────────────────
  {
    reportId: 'FS_REGISTER',
    engineType: 'SalesRegister',
    rendererProfile: 'Operational',
    title: 'Fuel Sales Register',
    titleUr: 'فیول سیلز رجسٹر',
    queryPlan: { base: 'SALES' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager', 'Accountant', 'Supervisor'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'totalSales', label: 'Total Revenue', labelUr: 'کل آمدن', formulaId: 'FORMULA_GROSS_REVENUE', displayType: 'simple', unit: '₨' },
      { id: 'totalLiters', label: 'Total Liters', labelUr: 'کل لیٹر', formulaId: 'FORMULA_TOTAL_LITERS_SOLD', displayType: 'simple', unit: 'L' },
      { id: 'txnTickets', label: 'Invoices', labelUr: 'انوائسز', displayType: 'simple', unit: '' },
    ],
    register: {
      columns: [
        { id: 'date', header: 'Date', headerUr: 'تاریخ', accessor: 'date', isDate: true, sortable: true, filterable: true },
        { id: 'invoiceNo', header: 'Invoice #', headerUr: 'انوائس #', accessor: 'invoiceNo', sortable: true, filterable: true },
        { id: 'productName', header: 'Product', headerUr: 'پروڈکٹ', accessor: 'productName', sortable: true, filterable: true },
        { id: 'quantity', header: 'Quantity (L)', headerUr: 'مقدار', accessor: 'quantity', isNumeric: true, sortable: true },
        { id: 'rate', header: 'Rate (₨)', headerUr: 'قیمت', accessor: 'rate', isCurrency: true },
        { id: 'totalAmount', header: 'Amount', headerUr: 'رقم', accessor: 'totalAmount', isCurrency: true, sortable: true },
        { id: 'paymentMethod', header: 'Payment Mode', headerUr: 'ادائیگی طریقہ', accessor: 'paymentMethod', sortable: true, filterable: true },
        { id: 'shiftId', header: 'Shift #', headerUr: 'شفٹ #', accessor: 'shiftId', filterable: true },
      ],
      defaultSortColumn: 'date',
      defaultSortDirection: 'desc',
      summaryFields: ['quantity', 'totalAmount'],
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
    searchConfig: {
      placeholder: '🔍 Search Invoice #, Product, Payment Mode, Shift #...',
      placeholderUr: '🔍 انوائس #، پروڈکٹ، ادائیگی طریقہ تلاش کریں...',
      searchFields: ['invoiceNo', 'productName', 'paymentMethod', 'shiftId'],
    },
    filterGroups: [
      {
        id: 'product', label: 'Product', labelUr: 'پروڈکٹ', type: 'pills', source: 'static',
        options: [
          { value: 'Petrol', label: 'Petrol', labelUr: 'پٹرول', icon: '🟢' },
          { value: 'Diesel', label: 'Diesel', labelUr: 'ڈیزل', icon: '🟤' },
          { value: 'CNG', label: 'CNG', labelUr: 'سی این جی', icon: '🔵' },
        ],
      },
      {
        id: 'paymentMethod', label: 'Payment', labelUr: 'ادائیگی', type: 'pills', source: 'static',
        options: [
          { value: 'Cash', label: 'Cash', labelUr: 'نقد', icon: '💵' },
          { value: 'Bank', label: 'Bank', labelUr: 'بینک', icon: '🏦' },
          { value: 'Credit', label: 'Credit', labelUr: 'ادھار', icon: '📋' },
        ],
      },
    ],
    quickActions: [
      { id: 'newSale', label: '+ New Sale', labelUr: '+ نئی سیل', icon: '⛽', targetReportId: 'A', color: 'emerald' },
      { id: 'exportExcel', label: 'Export Excel', labelUr: 'ایکسل رپورٹ', icon: '📊', targetReportId: 'FS_REGISTER', color: 'blue' },
    ],
  },
  {
    reportId: 'FS_PRODUCT',
    engineType: 'SalesRegister',
    rendererProfile: 'Operational',
    title: 'Product Wise Sales',
    titleUr: 'پروڈکٹ وائز سیلز',
    queryPlan: { base: 'SALES' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager', 'Accountant'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'petrolRevenue', label: 'Petrol Sales', labelUr: 'پٹرول سیلز', displayType: 'simple', unit: '₨' },
      { id: 'dieselRevenue', label: 'Diesel Sales', labelUr: 'ڈیزل سیلز', displayType: 'simple', unit: '₨' },
      { id: 'cngRevenue', label: 'CNG Sales', labelUr: 'سی این جی سیلز', displayType: 'simple', unit: '₨' },
    ],
    register: {
      columns: [
        { id: 'productName', header: 'Product', headerUr: 'پروڈکٹ', accessor: 'productName', sortable: true },
        { id: 'quantity', header: 'Total Liters', headerUr: 'کل لیٹر', accessor: 'quantity', isNumeric: true, sortable: true },
        { id: 'avgRate', header: 'Avg Rate', headerUr: 'اوسط قیمت', accessor: 'rate', isCurrency: true },
        { id: 'totalAmount', header: 'Total Revenue', headerUr: 'کل آمدن', accessor: 'totalAmount', isCurrency: true, sortable: true },
      ],
      defaultSortColumn: 'totalAmount',
      defaultSortDirection: 'desc',
      summaryFields: ['quantity', 'totalAmount'],
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
    searchConfig: {
      placeholder: '🔍 Search Product Name...',
      placeholderUr: '🔍 پروڈکٹ نام تلاش کریں...',
      searchFields: ['productName'],
    },
  },
  {
    reportId: 'FS_NOZZLE',
    engineType: 'SalesRegister',
    rendererProfile: 'Operational',
    title: 'Nozzle Wise Sales',
    titleUr: 'نوزل وائز سیلز',
    queryPlan: { base: 'SALES' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager', 'Supervisor'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'activeNozzles', label: 'Active Nozzles', labelUr: 'فعال نوزلز', displayType: 'simple', unit: '' },
      { id: 'totalDispensed', label: 'Total Liters Dispensed', labelUr: 'کل ڈسپنس شدہ لیٹر', displayType: 'simple', unit: 'L' },
    ],
    register: {
      columns: [
        { id: 'nozzleNo', header: 'Nozzle #', headerUr: 'نوزل #', accessor: 'nozzleNo', sortable: true },
        { id: 'productName', header: 'Product', headerUr: 'پروڈکٹ', accessor: 'productName', sortable: true },
        { id: 'quantity', header: 'Volume (L)', headerUr: 'حجم (لیٹر)', accessor: 'quantity', isNumeric: true, sortable: true },
        { id: 'totalAmount', header: 'Sales Amount', headerUr: 'سیل رقم', accessor: 'totalAmount', isCurrency: true, sortable: true },
      ],
      defaultSortColumn: 'quantity',
      defaultSortDirection: 'desc',
      summaryFields: ['quantity', 'totalAmount'],
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'FS_TANK',
    engineType: 'StockDashboard',
    rendererProfile: 'Inventory',
    title: 'Tank Wise Sales',
    titleUr: 'ٹینک وائز سیلز',
    queryPlan: { base: 'TANKS', joins: [{ collection: 'SALES', on: '_id' }] },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'tanksCount', label: 'Total Tanks', labelUr: 'کل ٹینکس', displayType: 'simple', unit: '' },
      { id: 'totalStockSales', label: 'Total Tank Outflow', labelUr: 'ٹینک نکلواٹ', displayType: 'simple', unit: 'L' },
    ],
    register: {
      columns: [
        { id: 'name', header: 'Tank Name', headerUr: 'ٹینک کا نام', accessor: 'name', sortable: true },
        { id: 'product', header: 'Product', headerUr: 'پروڈکٹ', accessor: 'product', sortable: true },
        { id: 'currentStock', header: 'Current Stock', headerUr: 'موجودہ اسٹاک', accessor: 'currentStock', isNumeric: true },
        { id: 'capacity', header: 'Capacity', headerUr: 'گنجائش', accessor: 'capacity', isNumeric: true },
      ],
      defaultSortColumn: 'name',
      defaultSortDirection: 'asc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'FS_COMPARE',
    engineType: 'SalesRegister',
    rendererProfile: 'Executive',
    title: 'Sales Comparison',
    titleUr: 'سیلز موازنہ',
    queryPlan: { base: 'SALES' },
    cacheTier: 'cached',
    visibleTo: ['Owner', 'Manager'],
    performanceBudgetMs: 3000,
    kpis: [
      { id: 'todayVsYesterday', label: 'Today vs Yesterday', labelUr: 'آج بمقابلہ کل', displayType: 'simple', unit: '%' },
      { id: 'growthRate', label: 'Monthly Growth', labelUr: 'ماہانہ اضافہ', displayType: 'simple', unit: '%' },
    ],
    register: {
      columns: [
        { id: 'date', header: 'Date', headerUr: 'تاریخ', accessor: 'date', isDate: true, sortable: true },
        { id: 'productName', header: 'Product', headerUr: 'پروڈکٹ', accessor: 'productName' },
        { id: 'quantity', header: 'Liters Sold', headerUr: 'لیٹر فروخت', accessor: 'quantity', isNumeric: true },
        { id: 'totalAmount', header: 'Revenue', headerUr: 'آمدن', accessor: 'totalAmount', isCurrency: true },
      ],
      defaultSortColumn: 'date',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'FS_TRENDS',
    engineType: 'SalesRegister',
    rendererProfile: 'Executive',
    title: 'Sales Trends',
    titleUr: 'سیلز رجحانات',
    queryPlan: { base: 'SALES' },
    cacheTier: 'cached',
    visibleTo: ['Owner', 'Manager'],
    performanceBudgetMs: 3000,
    kpis: [
      { id: 'peakHour', label: 'Peak Sales Hour', labelUr: 'سب سے زیادہ سیل کا وقت', displayType: 'simple', unit: '' },
      { id: 'topProduct', label: 'Top Selling Grade', labelUr: 'بہترین فروخت پروڈکٹ', displayType: 'simple', unit: '' },
    ],
    register: {
      columns: [
        { id: 'date', header: 'Period', headerUr: 'دورانیہ', accessor: 'date', isDate: true, sortable: true },
        { id: 'productName', header: 'Product', headerUr: 'پروڈکٹ', accessor: 'productName' },
        { id: 'quantity', header: 'Volume (L)', headerUr: 'حجم (لیٹر)', accessor: 'quantity', isNumeric: true },
        { id: 'totalAmount', header: 'Sales Amount', headerUr: 'سیل رقم', accessor: 'totalAmount', isCurrency: true },
      ],
      defaultSortColumn: 'date',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },

  // ──────────────────────────────────────────────
  // 📦 INVENTORY & STOCK
  // ──────────────────────────────────────────────
  {
    reportId: 'INV_TANK_REG',
    engineType: 'StockDashboard',
    rendererProfile: 'Inventory',
    title: 'Tank Stock Register',
    titleUr: 'ٹینک اسٹاک رجسٹر',
    queryPlan: { base: 'TANKS' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager', 'Supervisor'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'totalTankCapacity', label: 'Total Capacity', labelUr: 'کل گنجائش', displayType: 'simple', unit: 'L' },
      { id: 'totalStockOnHand', label: 'Stock On Hand', labelUr: 'موجودہ اسٹاک', displayType: 'simple', unit: 'L' },
      { id: 'avgFillPercent', label: 'Avg Fill %', labelUr: 'اوسط بھرائی %', displayType: 'gauge', unit: '%' },
    ],
    register: {
      columns: [
        { id: 'name', header: 'Tank Name', headerUr: 'ٹینک کا نام', accessor: 'name', sortable: true, filterable: true },
        { id: 'product', header: 'Product', headerUr: 'پروڈکٹ', accessor: 'product', sortable: true, filterable: true },
        { id: 'capacity', header: 'Capacity (L)', headerUr: 'گنجائش', accessor: 'capacity', isNumeric: true },
        { id: 'currentStock', header: 'Current Stock (L)', headerUr: 'موجودہ اسٹاک', accessor: 'currentStock', isNumeric: true, sortable: true },
        { id: 'status', header: 'Stock Status', headerUr: 'حالت', accessor: 'status', isStatus: true },
      ],
      defaultSortColumn: 'name',
      defaultSortDirection: 'asc',
      summaryFields: ['capacity', 'currentStock'],
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
    searchConfig: {
      placeholder: '🔍 Search Tank Name, Product...',
      placeholderUr: '🔍 ٹینک، پروڈکٹ تلاش کریں...',
      searchFields: ['name', 'product', 'status'],
    },
  },
  {
    reportId: 'INV_DIP',
    engineType: 'StockDashboard',
    rendererProfile: 'Inventory',
    title: 'Dip Readings Log',
    titleUr: 'ڈیپ ریڈنگز لاگ',
    queryPlan: { base: 'DIP_READINGS' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager', 'Supervisor'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'dipsToday', label: 'Dips Recorded Today', labelUr: 'آج ریکارڈ شدہ ڈیپس', displayType: 'simple', unit: '' },
    ],
    register: {
      columns: [
        { id: 'date', header: 'Date & Time', headerUr: 'تاریخ و وقت', accessor: 'date', isDate: true, sortable: true },
        { id: 'tankName', header: 'Tank Name', headerUr: 'ٹینک کا نام', accessor: 'tankName', sortable: true },
        { id: 'dipMm', header: 'Dip Level (mm)', headerUr: 'ڈیپ لیول (ملی میٹر)', accessor: 'dipMm', isNumeric: true },
        { id: 'dipLiters', header: 'Calculated Stock (L)', headerUr: 'حساب شدہ اسٹاک', accessor: 'dipLiters', isNumeric: true },
        { id: 'operator', header: 'Recorded By', headerUr: 'ریکارڈ کنندہ', accessor: 'operator' },
      ],
      defaultSortColumn: 'date',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'INV_MOVEMENT',
    engineType: 'StockDashboard',
    rendererProfile: 'Inventory',
    title: 'Fuel Stock Movement',
    titleUr: 'اسٹاک موومنٹ',
    queryPlan: { base: 'TANKS' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'openingStock', label: 'Opening Total', labelUr: 'اوپننگ اسٹاک', displayType: 'simple', unit: 'L' },
      { id: 'receivedTotal', label: 'Total Purchases In', labelUr: 'کل خریدا گیا اسٹاک', displayType: 'simple', unit: 'L' },
      { id: 'soldTotal', label: 'Total Sales Out', labelUr: 'کل فروخت شدہ اسٹاک', displayType: 'simple', unit: 'L' },
      { id: 'closingTotal', label: 'Closing Total', labelUr: 'کلوزنگ اسٹاک', displayType: 'simple', unit: 'L' },
    ],
    register: {
      columns: [
        { id: 'date', header: 'Date', headerUr: 'تاریخ', accessor: 'date', isDate: true, sortable: true },
        { id: 'tankName', header: 'Tank', headerUr: 'ٹینک', accessor: 'name', sortable: true },
        { id: 'product', header: 'Product', headerUr: 'پروڈکٹ', accessor: 'product' },
        { id: 'openingStock', header: 'Opening Stock', headerUr: 'اوپننگ اسٹاک', accessor: 'openingStock', isNumeric: true },
        { id: 'received', header: 'Stock Received', headerUr: 'موصولہ اسٹاک', accessor: 'received', isNumeric: true },
        { id: 'sold', header: 'Stock Sold', headerUr: 'فروخت شدہ', accessor: 'sold', isNumeric: true },
        { id: 'closingStock', header: 'Closing Stock', headerUr: 'کلوزنگ اسٹاک', accessor: 'currentStock', isNumeric: true },
      ],
      defaultSortColumn: 'date',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'INV_OPENING',
    engineType: 'StockDashboard',
    rendererProfile: 'Inventory',
    title: 'Opening Stock Register',
    titleUr: 'اوپننگ اسٹاک رجسٹر',
    queryPlan: { base: 'TANKS' },
    cacheTier: 'cached',
    visibleTo: ['Owner', 'Manager', 'Accountant'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'initialValuation', label: 'Initial Inventory Value', labelUr: 'ابتدائی انوینٹری مالیت', displayType: 'simple', unit: '₨' },
    ],
    register: {
      columns: [
        { id: 'name', header: 'Tank Name', headerUr: 'ٹینک کا نام', accessor: 'name', sortable: true },
        { id: 'product', header: 'Product', headerUr: 'پروڈکٹ', accessor: 'product' },
        { id: 'openingStock', header: 'Opening Liters', headerUr: 'اوپننگ لیٹر', accessor: 'openingStock', isNumeric: true },
        { id: 'rate', header: 'Rate (₨)', headerUr: 'قیمت', accessor: 'rate', isCurrency: true },
      ],
      defaultSortColumn: 'name',
      defaultSortDirection: 'asc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'INV_ADJUST',
    engineType: 'StockDashboard',
    rendererProfile: 'Inventory',
    title: 'Stock Adjustments',
    titleUr: 'اسٹاک ایڈجسٹمنٹ',
    queryPlan: { base: 'TANKS' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'adjustCount', label: 'Adjustment Entries', labelUr: 'ایڈجسٹمنٹ اندراجات', displayType: 'simple', unit: '' },
    ],
    register: {
      columns: [
        { id: 'date', header: 'Date', headerUr: 'تاریخ', accessor: 'date', isDate: true, sortable: true },
        { id: 'tankName', header: 'Tank Name', headerUr: 'ٹینک', accessor: 'name' },
        { id: 'adjustmentType', header: 'Type', headerUr: 'قسم', accessor: 'type' },
        { id: 'quantity', header: 'Quantity (L)', headerUr: 'مقدار', accessor: 'quantity', isNumeric: true },
        { id: 'reason', header: 'Reason / Note', headerUr: 'وجہ', accessor: 'reason' },
      ],
      defaultSortColumn: 'date',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'INV_RECON',
    engineType: 'StockDashboard',
    rendererProfile: 'Inventory',
    title: 'Stock Reconciliation',
    titleUr: 'اسٹاک ری کنسیلیشن',
    queryPlan: { base: 'TANKS' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'reconciledStatus', label: 'Reconciliation Balance', labelUr: 'توازن کی حالت', displayType: 'simple', unit: '' },
    ],
    register: {
      columns: [
        { id: 'name', header: 'Tank Name', headerUr: 'ٹینک کا نام', accessor: 'name', sortable: true },
        { id: 'product', header: 'Product', headerUr: 'پروڈکٹ', accessor: 'product' },
        { id: 'bookStock', header: 'Book Stock (L)', headerUr: 'بک اسٹاک', accessor: 'currentStock', isNumeric: true },
        { id: 'dipStock', header: 'Physical Dip Stock (L)', headerUr: 'ڈیپ اسٹاک', accessor: 'physicalStock', isNumeric: true },
        { id: 'diff', header: 'Variance (L)', headerUr: 'فرق', accessor: 'variance', isNumeric: true },
      ],
      defaultSortColumn: 'name',
      defaultSortDirection: 'asc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'INV_LOSS',
    engineType: 'Variance',
    rendererProfile: 'Inventory',
    title: 'Stock Loss / Gain',
    titleUr: 'اسٹاک نقصان / منافع',
    queryPlan: { base: 'TANKS' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'netGainLoss', label: 'Net Stock Gain/Loss', labelUr: 'خالص نقصان/منافع', displayType: 'simple', unit: 'L' },
      { id: 'gainLossValue', label: 'Financial Impact', labelUr: 'مالی اثرات', displayType: 'simple', unit: '₨' },
    ],
    register: {
      columns: [
        { id: 'date', header: 'Date', headerUr: 'تاریخ', accessor: 'date', isDate: true, sortable: true },
        { id: 'tankName', header: 'Tank', headerUr: 'ٹینک', accessor: 'name' },
        { id: 'product', header: 'Product', headerUr: 'پروڈکٹ', accessor: 'product' },
        { id: 'lossLiters', header: 'Loss/Gain (L)', headerUr: 'نقصان/منافع (لیٹر)', accessor: 'lossLiters', isNumeric: true },
        { id: 'amount', header: 'Value Impact (₨)', headerUr: 'مالی اثر', accessor: 'amount', isCurrency: true },
      ],
      defaultSortColumn: 'date',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },

  // ──────────────────────────────────────────────
  // 🛒 PURCHASES
  // ──────────────────────────────────────────────
  {
    reportId: 'PUR_HISTORY',
    engineType: 'SalesRegister',
    rendererProfile: 'Operational',
    title: 'Purchase History',
    titleUr: 'خریداری کی تاریخ',
    queryPlan: { base: 'FUEL_PURCHASES', joins: [{ collection: 'SUPPLIERS', on: '_id' }] },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager', 'Accountant'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'totalPurchases', label: 'Total Purchase Spend', labelUr: 'کل خریداری لاگت', displayType: 'simple', unit: '₨' },
      { id: 'petrolLitersPur', label: 'Petrol Purchased', labelUr: 'پٹرول خریداری', displayType: 'simple', unit: 'L' },
      { id: 'dieselLitersPur', label: 'Diesel Purchased', labelUr: 'ڈیزل خریداری', displayType: 'simple', unit: 'L' },
      { id: 'avgCostPerLiter', label: 'Avg Purchase Cost', labelUr: 'اوسط خریداری قیمت', displayType: 'simple', unit: '₨' },
    ],
    register: {
      columns: [
        { id: 'date', header: 'Date', headerUr: 'تاریخ', accessor: 'date', isDate: true, sortable: true, filterable: true },
        { id: 'invoiceNo', header: 'Invoice #', headerUr: 'انوائس #', accessor: 'invoiceNo', sortable: true, filterable: true },
        { id: 'supplierName', header: 'Supplier Name', headerUr: 'سپلائر کا نام', accessor: 'supplierName', sortable: true, filterable: true },
        { id: 'product', header: 'Product', headerUr: 'پروڈکٹ', accessor: 'product', sortable: true, filterable: true },
        { id: 'liters', header: 'Liters Delivered', headerUr: 'لیٹر ڈیلیوری', accessor: 'liters', isNumeric: true, sortable: true },
        { id: 'rate', header: 'Cost Rate', headerUr: 'خریداری ریٹ', accessor: 'rate', isCurrency: true },
        { id: 'totalAmount', header: 'Total Amount', headerUr: 'کل رقم', accessor: 'totalAmount', isCurrency: true, sortable: true },
        { id: 'status', header: 'Payment Status', headerUr: 'حالت', accessor: 'status', isStatus: true },
      ],
      defaultSortColumn: 'date',
      defaultSortDirection: 'desc',
      summaryFields: ['liters', 'totalAmount'],
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
    searchConfig: {
      placeholder: '🔍 Search Supplier, Invoice #, Product...',
      placeholderUr: '🔍 سپلائر، انوائس #، پروڈکٹ تلاش کریں...',
      searchFields: ['supplierName', 'invoiceNo', 'product', 'status'],
    },
    filterGroups: [
      {
        id: 'product', label: 'Product', labelUr: 'پروڈکٹ', type: 'pills', source: 'static',
        options: [
          { value: 'Petrol', label: 'Petrol', labelUr: 'پٹرول', icon: '🟢' },
          { value: 'Diesel', label: 'Diesel', labelUr: 'ڈیزل', icon: '🟤' },
        ],
      },
    ],
    quickActions: [
      { id: 'newPurchase', label: '+ New Fuel Order', labelUr: '+ نیا آڈر', icon: '🛒', targetReportId: 'PUR_HISTORY', color: 'blue' },
    ],
  },
  {
    reportId: 'PUR_REGISTER',
    engineType: 'SalesRegister',
    rendererProfile: 'Operational',
    title: 'Purchase Register',
    titleUr: 'خریداری رجسٹر',
    queryPlan: { base: 'FUEL_PURCHASES' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager', 'Accountant'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'totalPurchasesReg', label: 'Total Invoices', labelUr: 'کل انوائسز', displayType: 'simple', unit: '' },
      { id: 'totalPurAmount', label: 'Total Value', labelUr: 'کل مالیات', displayType: 'simple', unit: '₨' },
    ],
    register: {
      columns: [
        { id: 'date', header: 'Date', headerUr: 'تاریخ', accessor: 'date', isDate: true, sortable: true },
        { id: 'invoiceNo', header: 'Bill #', headerUr: 'بل #', accessor: 'invoiceNo', sortable: true },
        { id: 'supplierName', header: 'Supplier', headerUr: 'سپلائر', accessor: 'supplierName', sortable: true },
        { id: 'product', header: 'Product', headerUr: 'پروڈکٹ', accessor: 'product' },
        { id: 'liters', header: 'Liters', headerUr: 'لیٹر', accessor: 'liters', isNumeric: true },
        { id: 'totalAmount', header: 'Net Amount', headerUr: 'خالص رقم', accessor: 'totalAmount', isCurrency: true },
      ],
      defaultSortColumn: 'date',
      defaultSortDirection: 'desc',
      summaryFields: ['liters', 'totalAmount'],
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'PUR_DELIVERIES',
    engineType: 'SalesRegister',
    rendererProfile: 'Operational',
    title: 'Supplier Deliveries Log',
    titleUr: 'سپلائر ڈیلیوریز',
    queryPlan: { base: 'FUEL_PURCHASES' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'deliveriesToday', label: 'Deliveries Today', labelUr: 'آج کی ڈیلیوریز', displayType: 'simple', unit: '' },
    ],
    register: {
      columns: [
        { id: 'date', header: 'Delivery Time', headerUr: 'ڈیلیوری وقت', accessor: 'date', isDate: true, sortable: true },
        { id: 'supplierName', header: 'Supplier', headerUr: 'سپلائر', accessor: 'supplierName', sortable: true },
        { id: 'vehicleNo', header: 'Bowser / Vehicle #', headerUr: 'گاڑی #', accessor: 'vehicleNo' },
        { id: 'product', header: 'Product', headerUr: 'پروڈکٹ', accessor: 'product' },
        { id: 'liters', header: 'Quantity (L)', headerUr: 'مقدار', accessor: 'liters', isNumeric: true },
      ],
      defaultSortColumn: 'date',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'PUR_PENDING',
    engineType: 'SalesRegister',
    rendererProfile: 'Operational',
    title: 'Pending Supplier Deliveries',
    titleUr: 'زیر التوا ڈیلیوریز',
    queryPlan: { base: 'FUEL_PURCHASES' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'pendingOrdersCount', label: 'Orders Pending', labelUr: 'زیر التوا آرڈرز', displayType: 'simple', unit: '' },
    ],
    register: {
      columns: [
        { id: 'date', header: 'Order Date', headerUr: 'آرڈر تاریخ', accessor: 'date', isDate: true, sortable: true },
        { id: 'supplierName', header: 'Supplier', headerUr: 'سپلائر', accessor: 'supplierName' },
        { id: 'product', header: 'Product', headerUr: 'پروڈکٹ', accessor: 'product' },
        { id: 'liters', header: 'Ordered Liters', headerUr: 'آرڈر شدہ لیٹر', accessor: 'liters', isNumeric: true },
        { id: 'status', header: 'Status', headerUr: 'حالت', accessor: 'status', isStatus: true },
      ],
      defaultSortColumn: 'date',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'PUR_RETURNS',
    engineType: 'SalesRegister',
    rendererProfile: 'Operational',
    title: 'Purchase Returns',
    titleUr: 'خریداری واپسی',
    queryPlan: { base: 'RETURNS' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager', 'Accountant'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'returnsTotal', label: 'Returned Liters', labelUr: 'واپس شدہ لیٹر', displayType: 'simple', unit: 'L' },
    ],
    register: {
      columns: [
        { id: 'date', header: 'Return Date', headerUr: 'واپسی تاریخ', accessor: 'date', isDate: true, sortable: true },
        { id: 'supplierName', header: 'Supplier', headerUr: 'سپلائر', accessor: 'supplierName' },
        { id: 'product', header: 'Product', headerUr: 'پروڈکٹ', accessor: 'product' },
        { id: 'liters', header: 'Liters Returned', headerUr: 'لیٹر واپسی', accessor: 'liters', isNumeric: true },
        { id: 'amount', header: 'Refund Value', headerUr: 'واپسی رقم', accessor: 'totalAmount', isCurrency: true },
      ],
      defaultSortColumn: 'date',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'PUR_COMPARE',
    engineType: 'SalesRegister',
    rendererProfile: 'Executive',
    title: 'Purchase Rate Comparison',
    titleUr: 'خریداری موازنہ',
    queryPlan: { base: 'FUEL_PURCHASES' },
    cacheTier: 'cached',
    visibleTo: ['Owner', 'Manager'],
    performanceBudgetMs: 3000,
    kpis: [
      { id: 'bestSupplierRate', label: 'Lowest Rate Paid', labelUr: 'کم ترین خریدی قیمت', displayType: 'simple', unit: '₨' },
    ],
    register: {
      columns: [
        { id: 'supplierName', header: 'Supplier', headerUr: 'سپلائر', accessor: 'supplierName', sortable: true },
        { id: 'product', header: 'Product', headerUr: 'پروڈکٹ', accessor: 'product' },
        { id: 'avgRate', header: 'Avg Cost/L', headerUr: 'اوسط لاگت', accessor: 'rate', isCurrency: true },
        { id: 'totalLiters', header: 'Total Volume', headerUr: 'کل حجم', accessor: 'liters', isNumeric: true },
        { id: 'totalSpent', header: 'Total Spend', headerUr: 'کل خرچ', accessor: 'totalAmount', isCurrency: true },
      ],
      defaultSortColumn: 'totalSpent',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },

  // ──────────────────────────────────────────────
  // 💰 FINANCE
  // ──────────────────────────────────────────────
  {
    reportId: 'FIN_CASHBOOK',
    engineType: 'CashSummary',
    rendererProfile: 'Financial',
    title: 'Cash Book',
    titleUr: 'کیش بک',
    queryPlan: { base: 'CASH_LEDGER' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager', 'Accountant'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'openingCashBalance', label: 'Opening Cash', labelUr: 'ابتدائی نقد', displayType: 'simple', unit: '₨' },
      { id: 'cashInflow', label: 'Cash Received', labelUr: 'کیش آمد', displayType: 'simple', unit: '₨' },
      { id: 'cashOutflow', label: 'Cash Paid Out', labelUr: 'کیش ادا', displayType: 'simple', unit: '₨' },
      { id: 'closingCashBalance', label: 'Closing Cash Position', labelUr: 'موجودہ کیش بیلنس', displayType: 'simple', unit: '₨' },
    ],
    register: {
      columns: [
        { id: 'date', header: 'Date', headerUr: 'تاریخ', accessor: 'date', isDate: true, sortable: true },
        { id: 'voucherNo', header: 'Voucher #', headerUr: 'واؤچر #', accessor: 'voucherNo', sortable: true },
        { id: 'description', header: 'Particulars / Description', headerUr: 'تفصیل', accessor: 'description', filterable: true },
        { id: 'type', header: 'In / Out', headerUr: 'آمد / خرچ', accessor: 'type', isStatus: true },
        { id: 'amount', header: 'Amount', headerUr: 'رقم', accessor: 'amount', isCurrency: true, sortable: true },
        { id: 'balance', header: 'Running Balance', headerUr: 'بقایا بیلنس', accessor: 'balance', isCurrency: true },
      ],
      defaultSortColumn: 'date',
      defaultSortDirection: 'desc',
      summaryFields: ['amount'],
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
    searchConfig: {
      placeholder: '🔍 Search Voucher #, Description...',
      placeholderUr: '🔍 واؤچر #، تفصیل تلاش کریں...',
      searchFields: ['voucherNo', 'description', 'type'],
    },
  },
  {
    reportId: 'FIN_BANK',
    engineType: 'CashSummary',
    rendererProfile: 'Financial',
    title: 'Bank Ledger Statement',
    titleUr: 'بینک لیجر',
    queryPlan: { base: 'BANK_TRANSACTIONS' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Accountant'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'bankBalanceTotal', label: 'Bank Total Balance', labelUr: 'بینک کل بیلنس', displayType: 'simple', unit: '₨' },
    ],
    register: {
      columns: [
        { id: 'date', header: 'Date', headerUr: 'تاریخ', accessor: 'date', isDate: true, sortable: true },
        { id: 'bankName', header: 'Bank Name', headerUr: 'بینک کا نام', accessor: 'bankName', sortable: true },
        { id: 'refNo', header: 'Ref / Cheque #', headerUr: 'حوالہ #', accessor: 'refNo' },
        { id: 'type', header: 'Type', headerUr: 'قسم', accessor: 'type', isStatus: true },
        { id: 'amount', header: 'Amount', headerUr: 'رقم', accessor: 'amount', isCurrency: true },
        { id: 'balance', header: 'Balance', headerUr: 'بیلنس', accessor: 'balance', isCurrency: true },
      ],
      defaultSortColumn: 'date',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'FIN_DIGITAL',
    engineType: 'CashSummary',
    rendererProfile: 'Financial',
    title: 'Digital Cash & Wallet Payments',
    titleUr: 'ڈیجیٹل کیش',
    queryPlan: { base: 'WALLET_TRANSACTIONS' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager', 'Accountant'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'digitalTotal', label: 'Digital Payments Total', labelUr: 'ڈیجیٹل وصولیاں', displayType: 'simple', unit: '₨' },
    ],
    register: {
      columns: [
        { id: 'date', header: 'Date', headerUr: 'تاریخ', accessor: 'date', isDate: true, sortable: true },
        { id: 'provider', header: 'Wallet Provider', headerUr: 'والٹ پرووائیڈر', accessor: 'provider', sortable: true },
        { id: 'txnId', header: 'Transaction ID', headerUr: 'ٹرانزیکشن آئی ڈی', accessor: 'txnId' },
        { id: 'amount', header: 'Amount Received', headerUr: 'وصول شدہ رقم', accessor: 'amount', isCurrency: true },
        { id: 'fee', header: 'Fee / Charge', headerUr: 'فیس', accessor: 'fee', isCurrency: true },
      ],
      defaultSortColumn: 'date',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'FIN_POSITION',
    engineType: 'CashSummary',
    rendererProfile: 'Financial',
    title: 'Consolidated Cash Position',
    titleUr: 'کیش پوزیشن',
    queryPlan: { base: 'CASH_LEDGER' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Accountant'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'liquidAssets', label: 'Total Liquid Liquidity', labelUr: 'کل نقد و بینک بیلنس', displayType: 'simple', unit: '₨' },
    ],
    register: {
      columns: [
        { id: 'accountType', header: 'Account Type', headerUr: 'کھاتے کی قسم', accessor: 'accountType', sortable: true },
        { id: 'name', header: 'Account Name', headerUr: 'نام', accessor: 'name', sortable: true },
        { id: 'balance', header: 'Current Balance', headerUr: 'موجودہ بیلنس', accessor: 'balance', isCurrency: true },
      ],
      defaultSortColumn: 'balance',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'FIN_PL',
    engineType: 'ProfitReport',
    rendererProfile: 'Financial',
    title: 'Profit & Loss Statement',
    titleUr: 'نفع و نقصان',
    queryPlan: { base: 'SALES' },
    cacheTier: 'cached',
    visibleTo: ['Owner'],
    performanceBudgetMs: 4000,
    kpis: [
      { id: 'revenueTotal', label: 'Total Revenue', labelUr: 'کل آمدن', displayType: 'simple', unit: '₨' },
      { id: 'cogsTotal', label: 'Cost of Goods Sold', labelUr: 'فروخت شدہ مال کی لاگت', displayType: 'simple', unit: '₨' },
      { id: 'grossMargin', label: 'Gross Margin', labelUr: 'خام منافع', displayType: 'simple', unit: '₨' },
      { id: 'netOperatingProfit', label: 'Net Profit', labelUr: 'خالص منافع', displayType: 'simple', unit: '₨' },
    ],
    register: {
      columns: [
        { id: 'category', header: 'Financial Category', headerUr: 'زمرہ', accessor: 'category', sortable: true },
        { id: 'amount', header: 'Amount (₨)', headerUr: 'رقم', accessor: 'amount', isCurrency: true },
      ],
      defaultSortColumn: 'amount',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'FIN_CLOSING',
    engineType: 'CashSummary',
    rendererProfile: 'Financial',
    title: 'Daily Shift Closing Summary',
    titleUr: 'روزانہ بندش',
    queryPlan: { base: 'SHIFTS' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'shiftsClosedToday', label: 'Shifts Closed Today', labelUr: 'آج کی بند شفٹس', displayType: 'simple', unit: '' },
    ],
    register: {
      columns: [
        { id: 'date', header: 'Date', headerUr: 'تاریخ', accessor: 'date', isDate: true, sortable: true },
        { id: 'shiftId', header: 'Shift #', headerUr: 'شفٹ #', accessor: 'shiftId', sortable: true },
        { id: 'operatorName', header: 'Operator', headerUr: 'آپریٹر', accessor: 'operatorName' },
        { id: 'totalSales', header: 'Shift Sales', headerUr: 'شفٹ سیلز', accessor: 'totalSales', isCurrency: true },
        { id: 'varianceAmount', header: 'Cash Difference', headerUr: 'فرق', accessor: 'varianceAmount', isCurrency: true },
        { id: 'status', header: 'Status', headerUr: 'حالت', accessor: 'status', isStatus: true },
      ],
      defaultSortColumn: 'date',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'FIN_EXPENSE',
    engineType: 'SalesRegister',
    rendererProfile: 'Operational',
    title: 'Station Expense Register',
    titleUr: 'اخراجات رجسٹر',
    queryPlan: { base: 'EXPENSES' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager', 'Accountant'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'totalExpensesToday', label: "Today's Expenses", labelUr: 'آج کے اخراجات', displayType: 'simple', unit: '₨' },
      { id: 'monthlyExpenses', label: 'Monthly Expenses', labelUr: 'ماہانہ اخراجات', displayType: 'simple', unit: '₨' },
    ],
    register: {
      columns: [
        { id: 'date', header: 'Date', headerUr: 'تاریخ', accessor: 'date', isDate: true, sortable: true },
        { id: 'expenseId', header: 'Voucher #', headerUr: 'واؤچر #', accessor: 'expenseId', sortable: true },
        { id: 'category', header: 'Category', headerUr: 'زمرہ', accessor: 'category', filterable: true },
        { id: 'description', header: 'Description / Reason', headerUr: 'تفصیل', accessor: 'description' },
        { id: 'amount', header: 'Amount', headerUr: 'رقم', accessor: 'amount', isCurrency: true, sortable: true },
        { id: 'paymentMethod', header: 'Paid Via', headerUr: 'ادائیگی بذریعہ', accessor: 'paymentMethod' },
      ],
      defaultSortColumn: 'date',
      defaultSortDirection: 'desc',
      summaryFields: ['amount'],
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
    searchConfig: {
      placeholder: '🔍 Search Category, Description...',
      placeholderUr: '🔍 زمرہ، تفصیل تلاش کریں...',
      searchFields: ['category', 'description', 'paymentMethod'],
    },
  },

  // ──────────────────────────────────────────────
  // 📒 LEDGERS
  // ──────────────────────────────────────────────
  {
    reportId: 'LED_SUPPLIER',
    engineType: 'CustomerLedger',
    rendererProfile: 'Financial',
    title: 'Supplier Account Ledger',
    titleUr: 'سپلائر لیجر',
    queryPlan: { base: 'SUPPLIERS' },
    cacheTier: 'cached',
    visibleTo: ['Owner', 'Manager', 'Accountant'],
    performanceBudgetMs: 3000,
    kpis: [
      { id: 'supplierPayablesTotal', label: 'Total Payable to Suppliers', labelUr: 'کل واجب الادا رقم', displayType: 'simple', unit: '₨' },
    ],
    register: {
      columns: [
        { id: 'name', header: 'Supplier Name', headerUr: 'سپلائر کا نام', accessor: 'name', sortable: true, filterable: true },
        { id: 'phone', header: 'Phone', headerUr: 'فون', accessor: 'phone' },
        { id: 'totalPurchases', header: 'Total Purchases', headerUr: 'کل خریداری', accessor: 'totalPurchases', isCurrency: true },
        { id: 'totalPaid', header: 'Total Paid', headerUr: 'کل ادا شدہ', accessor: 'totalPaid', isCurrency: true },
        { id: 'balance', header: 'Outstanding Balance', headerUr: 'بقایا بیلنس', accessor: 'balance', isCurrency: true, sortable: true },
      ],
      defaultSortColumn: 'balance',
      defaultSortDirection: 'desc',
      summaryFields: ['balance'],
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
    searchConfig: {
      placeholder: '🔍 Search Supplier Name, Phone...',
      placeholderUr: '🔍 سپلائر نام، فون تلاش کریں...',
      searchFields: ['name', 'phone'],
    },
  },
  {
    reportId: 'LED_STAFF',
    engineType: 'CustomerLedger',
    rendererProfile: 'Financial',
    title: 'Staff Salary & Advance Ledger',
    titleUr: 'اسٹاف لیجر',
    queryPlan: { base: 'EMPLOYEES' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'staffAdvancesTotal', label: 'Total Advances Outstanding', labelUr: 'کل ایڈوانس بقایا', displayType: 'simple', unit: '₨' },
    ],
    register: {
      columns: [
        { id: 'name', header: 'Staff Name', headerUr: 'اسٹاف نام', accessor: 'name', sortable: true },
        { id: 'role', header: 'Role / Position', headerUr: 'عہدہ', accessor: 'role' },
        { id: 'salary', header: 'Monthly Salary', headerUr: 'ماہانہ تنخواہ', accessor: 'salary', isCurrency: true },
        { id: 'advances', header: 'Advance Balance', headerUr: 'ایڈوانس بقایا', accessor: 'advances', isCurrency: true },
      ],
      defaultSortColumn: 'name',
      defaultSortDirection: 'asc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'LED_BANK',
    engineType: 'CustomerLedger',
    rendererProfile: 'Financial',
    title: 'Bank Accounts Summary Ledger',
    titleUr: 'بینک لیجر',
    queryPlan: { base: 'BANK_ACCOUNTS' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Accountant'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'bankAccountsTotal', label: 'Total Funds in Bank', labelUr: 'بینکوں میں کل فنڈز', displayType: 'simple', unit: '₨' },
    ],
    register: {
      columns: [
        { id: 'bankName', header: 'Bank Name', headerUr: 'بینک', accessor: 'bankName', sortable: true },
        { id: 'accountNo', header: 'Account #', headerUr: 'اکاؤنٹ #', accessor: 'accountNo' },
        { id: 'branch', header: 'Branch', headerUr: 'برانچ', accessor: 'branch' },
        { id: 'balance', header: 'Current Balance', headerUr: 'موجودہ بیلنس', accessor: 'balance', isCurrency: true },
      ],
      defaultSortColumn: 'balance',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'LED_WALLET',
    engineType: 'CustomerLedger',
    rendererProfile: 'Financial',
    title: 'Digital Wallet Balance Ledger',
    titleUr: 'ڈیجیٹل والیٹ لیجر',
    queryPlan: { base: 'WALLETS' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'walletsTotal', label: 'Total Digital Wallets', labelUr: 'ڈیجیٹل والیٹس کل بیلنس', displayType: 'simple', unit: '₨' },
    ],
    register: {
      columns: [
        { id: 'provider', header: 'Wallet Provider', headerUr: 'پرووائیڈر', accessor: 'provider', sortable: true },
        { id: 'accountTitle', header: 'Title', headerUr: 'عنوان', accessor: 'accountTitle' },
        { id: 'balance', header: 'Available Balance', headerUr: 'دستاب بیلنس', accessor: 'balance', isCurrency: true },
      ],
      defaultSortColumn: 'balance',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },

  // ──────────────────────────────────────────────
  // 👥 CUSTOMERS
  // ──────────────────────────────────────────────
  {
    reportId: 'CUS_REGISTER',
    engineType: 'CustomerLedger',
    rendererProfile: 'Operational',
    title: 'Customer Directory Register',
    titleUr: 'گاہک رجسٹر',
    queryPlan: { base: 'CUSTOMERS' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager', 'Accountant'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'totalCustomersCount', label: 'Registered Credit Customers', labelUr: 'رجسٹرڈ گاہک', displayType: 'simple', unit: '' },
    ],
    register: {
      columns: [
        { id: 'name', header: 'Customer Name', headerUr: 'کسٹمر نام', accessor: 'name', sortable: true, filterable: true },
        { id: 'phone', header: 'Phone', headerUr: 'فون', accessor: 'phone' },
        { id: 'creditLimit', header: 'Credit Limit', headerUr: 'حد اعتبار', accessor: 'creditLimit', isCurrency: true },
        { id: 'balance', header: 'Current Balance', headerUr: 'موجودہ بقایا', accessor: 'balance', isCurrency: true, sortable: true },
        { id: 'status', header: 'Status', headerUr: 'حالت', accessor: 'status', isStatus: true },
      ],
      defaultSortColumn: 'name',
      defaultSortDirection: 'asc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
    searchConfig: {
      placeholder: '🔍 Search Customer Name, Phone...',
      placeholderUr: '🔍 کسٹمر نام، فون تلاش کریں...',
      searchFields: ['name', 'phone'],
    },
  },
  {
    reportId: 'CUS_OUTSTANDING',
    engineType: 'CustomerLedger',
    rendererProfile: 'Financial',
    title: 'Customer Credit Outstanding',
    titleUr: 'کسٹمر بقایا جات',
    queryPlan: { base: 'CUSTOMERS' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager', 'Accountant'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'receivablesTotal', label: 'Total Customer Receivables', labelUr: 'کل واجب الوصول رقم', displayType: 'simple', unit: '₨' },
      { id: 'overdueCount', label: 'Overdue Customers', labelUr: 'تجاوز شدہ کسٹمرز', displayType: 'simple', unit: '' },
    ],
    register: {
      columns: [
        { id: 'name', header: 'Customer Name', headerUr: 'کسٹمر', accessor: 'name', sortable: true },
        { id: 'phone', header: 'Phone', headerUr: 'فون', accessor: 'phone' },
        { id: 'balance', header: 'Outstanding Due (₨)', headerUr: 'واجب الوصول رقم', accessor: 'balance', isCurrency: true, sortable: true },
        { id: 'creditLimit', header: 'Credit Limit (₨)', headerUr: 'حد اعتبار', accessor: 'creditLimit', isCurrency: true },
        { id: 'lastPaymentDate', header: 'Last Paid Date', headerUr: 'آخری ادائیگی', accessor: 'lastPaymentDate', isDate: true },
      ],
      defaultSortColumn: 'balance',
      defaultSortDirection: 'desc',
      summaryFields: ['balance'],
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
    searchConfig: {
      placeholder: '🔍 Search Customer...',
      placeholderUr: '🔍 کسٹمر تلاش کریں...',
      searchFields: ['name', 'phone'],
    },
  },
  {
    reportId: 'CUS_RECOVERY',
    engineType: 'SalesRegister',
    rendererProfile: 'Financial',
    title: 'Customer Recovery Receipts',
    titleUr: 'کسٹمر وصولی',
    queryPlan: { base: 'PAYMENTS' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager', 'Accountant'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'recoveredToday', label: 'Recovered Today', labelUr: 'آج کی وصولی', displayType: 'simple', unit: '₨' },
      { id: 'recoveredMonth', label: 'Recovered This Month', labelUr: 'اس ماہ کی وصولی', displayType: 'simple', unit: '₨' },
    ],
    register: {
      columns: [
        { id: 'date', header: 'Date', headerUr: 'تاریخ', accessor: 'date', isDate: true, sortable: true },
        { id: 'receiptNo', header: 'Receipt #', headerUr: 'رسید #', accessor: 'receiptNo', sortable: true },
        { id: 'customerName', header: 'Customer Name', headerUr: 'کسٹمر', accessor: 'customerName', filterable: true },
        { id: 'paymentMode', header: 'Mode', headerUr: 'طریقہ', accessor: 'paymentMode' },
        { id: 'amount', header: 'Amount Received', headerUr: 'وصول شدہ رقم', accessor: 'amount', isCurrency: true, sortable: true },
      ],
      defaultSortColumn: 'date',
      defaultSortDirection: 'desc',
      summaryFields: ['amount'],
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'CUS_AGING',
    engineType: 'CustomerLedger',
    rendererProfile: 'Financial',
    title: 'Customer Aging Analysis',
    titleUr: 'ایجنگ رپورٹ',
    queryPlan: { base: 'CUSTOMERS' },
    cacheTier: 'cached',
    visibleTo: ['Owner', 'Manager', 'Accountant'],
    performanceBudgetMs: 3000,
    kpis: [
      { id: 'totalOverdueAging', label: 'Overdue > 60 Days', labelUr: '60 دن سے زائد بقایا', displayType: 'simple', unit: '₨' },
    ],
    register: {
      columns: [
        { id: 'name', header: 'Customer Name', headerUr: 'کسٹمر', accessor: 'name', sortable: true },
        { id: 'current', header: '0 - 30 Days', headerUr: '0 تا 30 دن', accessor: 'current', isCurrency: true },
        { id: 'days30', header: '31 - 60 Days', headerUr: '31 تا 60 دن', accessor: 'days30', isCurrency: true },
        { id: 'days60', header: '61 - 90 Days', headerUr: '61 تا 90 دن', accessor: 'days60', isCurrency: true },
        { id: 'days90Plus', header: '90+ Days', headerUr: '90+ دن', accessor: 'days90Plus', isCurrency: true },
        { id: 'total', header: 'Total Outstanding', headerUr: 'کل بقایا', accessor: 'balance', isCurrency: true, sortable: true },
      ],
      defaultSortColumn: 'total',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },

  // ──────────────────────────────────────────────
  // 🚛 SUPPLIERS
  // ──────────────────────────────────────────────
  {
    reportId: 'SUP_REGISTER',
    engineType: 'CustomerLedger',
    rendererProfile: 'Operational',
    title: 'Supplier Register Directory',
    titleUr: 'سپلائر رجسٹر',
    queryPlan: { base: 'SUPPLIERS' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager', 'Accountant'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'suppliersCount', label: 'Active Fuel Oil Suppliers', labelUr: 'فعال سپلائرز', displayType: 'simple', unit: '' },
    ],
    register: {
      columns: [
        { id: 'name', header: 'Supplier Name', headerUr: 'سپلائر کا نام', accessor: 'name', sortable: true },
        { id: 'contactPerson', header: 'Contact Person', headerUr: 'رابطہ شخص', accessor: 'contactPerson' },
        { id: 'phone', header: 'Phone', headerUr: 'فون', accessor: 'phone' },
        { id: 'balance', header: 'Payable Balance', headerUr: 'واجب الادا بیلنس', accessor: 'balance', isCurrency: true, sortable: true },
      ],
      defaultSortColumn: 'name',
      defaultSortDirection: 'asc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'SUP_OUTSTANDING',
    engineType: 'CustomerLedger',
    rendererProfile: 'Financial',
    title: 'Supplier Outstanding Balances',
    titleUr: 'سپلائر بقایا جات',
    queryPlan: { base: 'SUPPLIERS' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager', 'Accountant'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'supplierTotalPayable', label: 'Total Supplier Payables', labelUr: 'کل واجب الادا رقم', displayType: 'simple', unit: '₨' },
    ],
    register: {
      columns: [
        { id: 'name', header: 'Supplier Name', headerUr: 'سپلائر', accessor: 'name', sortable: true },
        { id: 'phone', header: 'Phone', headerUr: 'فون', accessor: 'phone' },
        { id: 'totalPurchases', header: 'Total Purchased', headerUr: 'کل خریداری', accessor: 'totalPurchases', isCurrency: true },
        { id: 'balance', header: 'Balance Outstanding', headerUr: 'بقایا رقم', accessor: 'balance', isCurrency: true, sortable: true },
      ],
      defaultSortColumn: 'balance',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'SUP_PAYMENTS',
    engineType: 'SalesRegister',
    rendererProfile: 'Financial',
    title: 'Supplier Payment History',
    titleUr: 'ادائیگیاں',
    queryPlan: { base: 'PAYMENTS' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager', 'Accountant'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'supplierPaidMonth', label: 'Paid to Suppliers (This Month)', labelUr: 'سپلائر ادائیگیاں اس ماہ', displayType: 'simple', unit: '₨' },
    ],
    register: {
      columns: [
        { id: 'date', header: 'Date', headerUr: 'تاریخ', accessor: 'date', isDate: true, sortable: true },
        { id: 'paymentNo', header: 'Payment #', headerUr: 'ادائیگی #', accessor: 'paymentNo', sortable: true },
        { id: 'supplierName', header: 'Supplier', headerUr: 'سپلائر', accessor: 'supplierName' },
        { id: 'amount', header: 'Amount Paid', headerUr: 'ادا شدہ رقم', accessor: 'amount', isCurrency: true, sortable: true },
        { id: 'paymentMode', header: 'Mode', headerUr: 'طریقہ', accessor: 'paymentMode' },
      ],
      defaultSortColumn: 'date',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'SUP_HISTORY',
    engineType: 'SalesRegister',
    rendererProfile: 'Operational',
    title: 'Supplier Supply History',
    titleUr: 'خریداری کی تاریخ',
    queryPlan: { base: 'FUEL_PURCHASES' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'totalDeliveriesCount', label: 'Total Supply Invoices', labelUr: 'کل سپلائی انوائسز', displayType: 'simple', unit: '' },
    ],
    register: {
      columns: [
        { id: 'date', header: 'Date', headerUr: 'تاریخ', accessor: 'date', isDate: true, sortable: true },
        { id: 'invoiceNo', header: 'Invoice #', headerUr: 'انوائس #', accessor: 'invoiceNo' },
        { id: 'supplierName', header: 'Supplier', headerUr: 'سپلائر', accessor: 'supplierName' },
        { id: 'product', header: 'Product', headerUr: 'پروڈکٹ', accessor: 'product' },
        { id: 'liters', header: 'Liters', headerUr: 'لیٹر', accessor: 'liters', isNumeric: true },
        { id: 'totalAmount', header: 'Amount', headerUr: 'رقم', accessor: 'totalAmount', isCurrency: true },
      ],
      defaultSortColumn: 'date',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },

  // ──────────────────────────────────────────────
  // 👨‍💼 STAFF
  // ──────────────────────────────────────────────
  {
    reportId: 'STF_PERFORMANCE',
    engineType: 'Variance',
    rendererProfile: 'Operational',
    title: 'Staff Sales Performance',
    titleUr: 'اسٹاف کارکردگی',
    queryPlan: { base: 'EMPLOYEES' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'topStaffSales', label: 'Top Sales Staff', labelUr: 'بہترین سیلز آپریٹر', displayType: 'simple', unit: '' },
    ],
    register: {
      columns: [
        { id: 'name', header: 'Staff Name', headerUr: 'اسٹاف نام', accessor: 'name', sortable: true },
        { id: 'role', header: 'Role', headerUr: 'عہدہ', accessor: 'role' },
        { id: 'shiftsCount', header: 'Shifts Worked', headerUr: 'شفٹس تفصیل', accessor: 'shiftsCount', isNumeric: true },
        { id: 'totalSalesVolume', header: 'Total Sales (L)', headerUr: 'کل سیلز لیٹر', accessor: 'totalSalesVolume', isNumeric: true },
        { id: 'varianceCount', header: 'Cash Variances', headerUr: 'فرق واقعات', accessor: 'varianceCount', isNumeric: true },
      ],
      defaultSortColumn: 'totalSalesVolume',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'STF_ATTENDANCE',
    engineType: 'SalesRegister',
    rendererProfile: 'Operational',
    title: 'Staff Daily Attendance Log',
    titleUr: 'حاضری',
    queryPlan: { base: 'ATTENDANCE' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'staffPresentToday', label: 'Present Today', labelUr: 'آج حاضر', displayType: 'simple', unit: '' },
    ],
    register: {
      columns: [
        { id: 'date', header: 'Date', headerUr: 'تاریخ', accessor: 'date', isDate: true, sortable: true },
        { id: 'staffName', header: 'Staff Name', headerUr: 'اسٹاف', accessor: 'staffName', sortable: true },
        { id: 'checkIn', header: 'Duty In', headerUr: 'ڈیوٹی آمد', accessor: 'checkIn' },
        { id: 'checkOut', header: 'Duty Out', headerUr: 'ڈیوٹی رخصت', accessor: 'checkOut' },
        { id: 'status', header: 'Status', headerUr: 'حالت', accessor: 'status', isStatus: true },
      ],
      defaultSortColumn: 'date',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'STF_SALARY',
    engineType: 'CustomerLedger',
    rendererProfile: 'Financial',
    title: 'Payroll & Salary Sheet',
    titleUr: 'تنخواہ',
    queryPlan: { base: 'EMPLOYEES' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'totalPayrollMonth', label: 'Total Monthly Payroll', labelUr: 'کل ماہانہ تنخواہیں', displayType: 'simple', unit: '₨' },
    ],
    register: {
      columns: [
        { id: 'name', header: 'Staff Name', headerUr: 'اسٹاف', accessor: 'name', sortable: true },
        { id: 'role', header: 'Designation', headerUr: 'عہدہ', accessor: 'role' },
        { id: 'salary', header: 'Base Salary', headerUr: 'بنیادی تنخواہ', accessor: 'salary', isCurrency: true },
        { id: 'advances', header: 'Deduction/Advance', headerUr: 'ایڈوانس کٹوتی', accessor: 'advances', isCurrency: true },
        { id: 'netPayable', header: 'Net Payable', headerUr: 'قابل ادائیگی', accessor: 'netPayable', isCurrency: true },
      ],
      defaultSortColumn: 'name',
      defaultSortDirection: 'asc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'STF_SHIFTS',
    engineType: 'SalesRegister',
    rendererProfile: 'Operational',
    title: 'Shift Assignment History',
    titleUr: 'شفٹ کی تاریخ',
    queryPlan: { base: 'SHIFTS' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'shiftsCompletedTotal', label: 'Completed Shifts', labelUr: 'مکمل شدہ شفٹس', displayType: 'simple', unit: '' },
    ],
    register: {
      columns: [
        { id: 'date', header: 'Date', headerUr: 'تاریخ', accessor: 'date', isDate: true, sortable: true },
        { id: 'shiftId', header: 'Shift #', headerUr: 'شفٹ #', accessor: 'shiftId', sortable: true },
        { id: 'operatorName', header: 'Operator', headerUr: 'آپریٹر', accessor: 'operatorName' },
        { id: 'totalSales', header: 'Shift Sales (₨)', headerUr: 'شفٹ سیلز', accessor: 'totalSales', isCurrency: true },
        { id: 'status', header: 'Status', headerUr: 'حالت', accessor: 'status', isStatus: true },
      ],
      defaultSortColumn: 'date',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },

  // ──────────────────────────────────────────────
  // ⚙ PRICING
  // ──────────────────────────────────────────────
  {
    reportId: 'PRC_HISTORY',
    engineType: 'SalesRegister',
    rendererProfile: 'Operational',
    title: 'Fuel Price Change Audit Log',
    titleUr: 'قیمت تبدیلی کی تاریخ',
    queryPlan: { base: 'FUEL_PRICES' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'lastPriceChangeDate', label: 'Latest Price Change', labelUr: 'آخری تبدیلی تاریخ', displayType: 'simple', unit: '' },
    ],
    register: {
      columns: [
        { id: 'effectiveDate', header: 'Effective Date', headerUr: 'تاریخ نافذ', accessor: 'effectiveDate', isDate: true, sortable: true },
        { id: 'product', header: 'Product', headerUr: 'پروڈکٹ', accessor: 'product', sortable: true },
        { id: 'oldPrice', header: 'Previous Rate (₨)', headerUr: 'سابقی قیمت', accessor: 'oldPrice', isCurrency: true },
        { id: 'newPrice', header: 'New Rate (₨)', headerUr: 'نئی قیمت', accessor: 'newPrice', isCurrency: true },
        { id: 'changedBy', header: 'Updated By', headerUr: 'تبدیل کنندہ', accessor: 'changedBy' },
      ],
      defaultSortColumn: 'effectiveDate',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'PRC_RATES',
    engineType: 'SalesRegister',
    rendererProfile: 'Operational',
    title: 'Active Product Fuel Rates',
    titleUr: 'پروڈکٹ ریٹس',
    queryPlan: { base: 'PRODUCTS' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager', 'Supervisor'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'petrolCurrentRate', label: 'Current Petrol Rate', labelUr: 'پٹرول قیمت', displayType: 'simple', unit: '₨' },
      { id: 'dieselCurrentRate', label: 'Current Diesel Rate', labelUr: 'ڈیزل قیمت', displayType: 'simple', unit: '₨' },
    ],
    register: {
      columns: [
        { id: 'productName', header: 'Product Name', headerUr: 'پروڈکٹ نام', accessor: 'productName', sortable: true },
        { id: 'purchaseRate', header: 'Purchase Rate (Cost)', headerUr: 'خریداری لاگت', accessor: 'purchaseRate', isCurrency: true },
        { id: 'saleRate', header: 'Sale Rate (Retail)', headerUr: 'فروخت قیمت', accessor: 'saleRate', isCurrency: true },
      ],
      defaultSortColumn: 'productName',
      defaultSortDirection: 'asc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'PRC_MARGIN',
    engineType: 'ProfitReport',
    rendererProfile: 'Financial',
    title: 'Product Fuel Margin Analysis',
    titleUr: 'مارجن تجزیہ',
    queryPlan: { base: 'PRODUCTS' },
    cacheTier: 'cached',
    visibleTo: ['Owner'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'avgMarginPerLiter', label: 'Avg Margin / Liter', labelUr: 'اوسط منافع پر لیٹر', displayType: 'simple', unit: '₨' },
    ],
    register: {
      columns: [
        { id: 'productName', header: 'Product Name', headerUr: 'پروڈکٹ نام', accessor: 'productName', sortable: true },
        { id: 'saleRate', header: 'Retail Price', headerUr: 'فروخت قیمت', accessor: 'saleRate', isCurrency: true },
        { id: 'purchaseRate', header: 'Purchase Cost', headerUr: 'خرید لاگت', accessor: 'purchaseRate', isCurrency: true },
        { id: 'marginPerLiter', header: 'Margin / Liter (₨)', headerUr: 'منافع پر لیٹر', accessor: 'marginPerLiter', isCurrency: true, sortable: true },
      ],
      defaultSortColumn: 'marginPerLiter',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },

  // ──────────────────────────────────────────────
  // 📈 ANALYTICS
  // ──────────────────────────────────────────────
  {
    reportId: 'ANL_EXEC',
    engineType: 'BusinessDashboard',
    rendererProfile: 'Executive',
    title: 'Executive Station Control Room',
    titleUr: 'ایگزیکٹو ڈیش بورڈ',
    queryPlan: { base: 'SALES' },
    cacheTier: 'realtime',
    visibleTo: ['Owner'],
    performanceBudgetMs: 2000,
    kpis: [
      { id: 'execRevenueToday', label: "Today's Gross Sales", labelUr: 'آج کی آمدن', displayType: 'simple', unit: '₨' },
      { id: 'execProfitToday', label: "Today's Estimated Net Profit", labelUr: 'آج کا خالص منافع', displayType: 'simple', unit: '₨' },
      { id: 'execFuelVolume', label: 'Fuel Volume Dispensed', labelUr: 'کل فروخت شدہ لیٹر', displayType: 'simple', unit: 'L' },
    ],
    register: {
      columns: [
        { id: 'date', header: 'Date', headerUr: 'تاریخ', accessor: 'date', isDate: true, sortable: true },
        { id: 'invoiceNo', header: 'Invoice #', headerUr: 'انوائس #', accessor: 'invoiceNo' },
        { id: 'productName', header: 'Product', headerUr: 'پروڈکٹ', accessor: 'productName' },
        { id: 'totalAmount', header: 'Amount', headerUr: 'رقم', accessor: 'totalAmount', isCurrency: true },
      ],
      defaultSortColumn: 'date',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'ANL_AI',
    engineType: 'BusinessDashboard',
    rendererProfile: 'Executive',
    title: 'Station AI Strategic Insights',
    titleUr: 'اے آئی بصیرت',
    queryPlan: { base: 'SALES' },
    cacheTier: 'realtime',
    visibleTo: ['Owner', 'Manager'],
    performanceBudgetMs: 3000,
    kpis: [
      { id: 'aiHealthScore', label: 'Station Operational Score', labelUr: 'اسٹیشن کی عمومی صحت', displayType: 'simple', unit: '%' },
    ],
    register: {
      columns: [
        { id: 'date', header: 'Date', headerUr: 'تاریخ', accessor: 'date', isDate: true },
        { id: 'category', header: 'Domain', headerUr: 'ڈومین', accessor: 'category' },
        { id: 'summary', header: 'AI Recommendation', headerUr: 'سفارش', accessor: 'summary' },
      ],
      defaultSortColumn: 'date',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'ANL_TRENDS',
    engineType: 'SalesRegister',
    rendererProfile: 'Executive',
    title: 'Multi-Month Business Trends',
    titleUr: 'رجحانات',
    queryPlan: { base: 'SALES' },
    cacheTier: 'cached',
    visibleTo: ['Owner', 'Manager'],
    performanceBudgetMs: 3000,
    kpis: [
      { id: 'volumeGrowth', label: 'Quarterly Volume Growth', labelUr: 'سہ ماہی حجم میں اضافہ', displayType: 'simple', unit: '%' },
    ],
    register: {
      columns: [
        { id: 'period', header: 'Month / Period', headerUr: 'دورانیہ', accessor: 'period', sortable: true },
        { id: 'volume', header: 'Volume Sold (L)', headerUr: 'حجم (لیٹر)', accessor: 'quantity', isNumeric: true },
        { id: 'revenue', header: 'Total Revenue', headerUr: 'آمدن', accessor: 'totalAmount', isCurrency: true },
      ],
      defaultSortColumn: 'period',
      defaultSortDirection: 'desc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
  {
    reportId: 'ANL_FORECAST',
    engineType: 'StockDashboard',
    rendererProfile: 'Executive',
    title: 'Fuel Demand & Stock Forecast',
    titleUr: 'پیشنگوئی',
    queryPlan: { base: 'TANKS' },
    cacheTier: 'cached',
    visibleTo: ['Owner', 'Manager'],
    performanceBudgetMs: 3000,
    kpis: [
      { id: 'predictedDepletion', label: 'Days Stock Remaining', labelUr: 'اسٹاک کے باقی ایام', displayType: 'simple', unit: 'Days' },
    ],
    register: {
      columns: [
        { id: 'product', header: 'Product', headerUr: 'پروڈکٹ', accessor: 'product', sortable: true },
        { id: 'currentStock', header: 'Current Stock (L)', headerUr: 'موجودہ اسٹاک', accessor: 'currentStock', isNumeric: true },
        { id: 'predictedDailySales', header: 'Est. Daily Sales (L)', headerUr: 'متوقع روزانہ سیل', accessor: 'predictedDailySales', isNumeric: true },
      ],
      defaultSortColumn: 'product',
      defaultSortDirection: 'asc',
    },
    exports: ['pdf', 'excel', 'csv', 'print'],
  },
];

/** Register all 54 report configs into ReportConfigRegistry */
export function registerAllBusinessReports(): void {
  for (const report of ALL_BUSINESS_REPORTS) {
    ReportConfigRegistry.register(report);
  }
}
